[package]
name = "advent_of_code_2020"
version = "0.1.0"
authors = ["Samuel Simplicio <samuelsimplicio@poli.ufrj.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
